# Introduction to Numpy

## Agenda
- Fundamentals of Numpy
  - Advantages
  - Installation
- Numpy Array Object
  - Creating Numpy Arrays.
- Attributes of Numpy arrays
- Numpy array Functions
- Arithmetic Operations using Numpy
- Statistical Operations
- String Functions in numpy
- Numpy Array Indexing
- Numpy Array Slicing

## Fundamentals of Numpy
Numpy(Numerical Python) is a free and open source library that is mostly for mathematical operations.
- it is used for working with arrays.
- it consists of multidimensional arrays , and function.
### Advantages
-  numpy is faster and better functions to deal with mathematical problems.

# Installation
To install numpy on any python environment use the code below
$$ \text{pip install numpy} $$


In [1]:
# install numpy
!pip install numpy

In [7]:
#pip install --upgrade numpy

In [8]:
# import numpy 
import numpy as np

import time

In [9]:
# How numpy is faster

In [10]:
# using numpy to create a data of 100000000 floating point numbers and calculate their mean

In [15]:
data = np.random.rand(100000000) # this generates random floating point numbers
data[:5]

array([0.44636688, 0.22049409, 0.25396305, 0.17318277, 0.25322581])

In [16]:
# mean calculation using numpy mean function
start = time.time()
mn =  np.mean(data)
stop = time.time()
print(f'Time Elasped {stop-start}')

Time Elasped 0.37842750549316406


In [17]:
# mean calculation using tradition python math
start = time.time()
mn_p =  sum(data)/len(data)
stop = time.time()
print(f'Time Elasped {stop-start}')

Time Elasped 16.153377294540405


## Numpy Array Object
An array is a data structure that arranges data of similar datatypes(Homogeneous) in a contiguous memory location. Each value inside the array is called as `element`, that can be accessed or modified using the `index` <br>
The arrays are often called ndarray(n dimensional array) in numpy. There are two ways by which an ndarray is craeted in numpy
- use numpy builtin function `array`
  - syntax is `np.array(list of values/scalar)`
- use numpy array generative functions


### Create Numpy arrays and see the attributes

In [31]:
# Create a 0 Dimensional array.(use a scalar value in array function)
arr0 = np.array(5)
print(arr0)
print(hex(id(arr0)))
# Attributes
print(arr0.data)
print(arr0.ndim) # gives the dimensions
print(arr0.itemsize)  # gives the memory allocated in bytes to each element
print(arr0.shape)  # gives the number of values in each dimension as a tuple
print(arr0.size) # gives the total number of elements in the array
print(arr0.dtype) # gives the data type of the elements of the array


5
0x11f1a62af70
0
4
()
1
int32


In [37]:
# Create a 1 Dimensional array.(use a list of  values in array function)
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(hex(id(arr1)))
# Attributes
print(arr1.data)
print(arr1.ndim) # gives the dimensions
print(arr1.itemsize)  # gives the memory allocated in bytes to each element
print(arr1.shape)  # gives the number of values in each dimension as a tuple
print(arr1.size) # gives the total number of elements in the array
print(arr1.dtype) # gives the data type of the elements of the array

[1 2 3 4 5]
0x11f1a790330
1
4
(5,)
5
int32


In [38]:
# Create a 2 Dimensional array.(use a list of lists values in array function)
arr2 = np.array([[1,2,3,4,5], [11,12,13,14,15]])
print(arr2)
print(hex(id(arr2)))
# Attributes
print(arr2.data)
print(arr2.ndim) # gives the dimensions
print(arr2.itemsize)  # gives the memory allocated in bytes to each element
print(arr2.shape)  # gives the number of values in each dimension as a tuple
print(arr2.size) # gives the total number of elements in the array
print(arr2.dtype) # gives the data type of the elements of the array

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
0x11f1a62b1b0
2
4
(2, 5)
10
int32


In [39]:
# Create a 3 Dimensional array.(use a list of lists of lists values in array function)
arr3 = np.array([[[1,2,3,4,5], [11,12,13,14,15]], [[21,22,23,24,25], [31,32,33,34,35]]])
print(arr3)
print(hex(id(arr3)))
# Attributes
print(arr3.data)
print(arr3.ndim) # gives the dimensions
print(arr3.itemsize)  # gives the memory allocated in bytes to each element
print(arr3.shape)  # gives the number of values in each dimension as a tuple
print(arr3.size) # gives the total number of elements in the array
print(arr3.dtype) # gives the data type of the elements of the array

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[21 22 23 24 25]
  [31 32 33 34 35]]]
0x11f1a62b630
3
4
(2, 2, 5)
20
int32
